name=JWS_Anim_Pro
version=1.0.0
author=Kawan Kreatif (Indonesia)
maintainer=Kawan Kreatif
sentence=Library Animasi Profesional untuk Jam Waktu Sholat (JWS) menggunakan ESP32 HUB75.
paragraph=Menyediakan animasi swimBox, running text, scroll vertical step, dan dim warna otomatis tanpa delay.
category=Display
url=https://github.com/username/JWS_Anim_Pro
architectures=esp32
